# Generated by Django 5.2.8 on 2025-11-14 10:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('instrumentation', 'Instrumentation & Control'), ('piping', 'Piping & Flow'), ('equipment', 'Equipment & Vessels'), ('safety', 'Safety Systems'), ('tagging', 'Tag Numbering'), ('drafting', 'Drafting Standards'), ('logical', 'Process Logic'), ('mechanical', 'Mechanical Design'), ('electrical', 'Electrical Systems'), ('utilities', 'Utilities & Services')], max_length=20)),
                ('description', models.TextField(help_text='Category description and scope')),
                ('color_code', models.CharField(default='#FF0000', help_text='Hex color for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Error Category',
                'verbose_name_plural': 'Error Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PIDDiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drawing_number', models.CharField(help_text="Drawing number (e.g., 'P&ID-100-001')", max_length=50)),
                ('drawing_title', models.CharField(help_text='Drawing title', max_length=200)),
                ('diagram_type', models.CharField(choices=[('process_flow', 'Process Flow Diagram (PFD)'), ('piping_instrumentation', 'Piping & Instrumentation Diagram (P&ID)'), ('utility_flow', 'Utility Flow Diagram (UFD)'), ('safety_shutdown', 'Safety Shutdown Diagram (SSD)'), ('fire_gas', 'Fire & Gas System (F&G)'), ('electrical_single', 'Electrical Single Line'), ('control_logic', 'Control Logic Diagram'), ('loop_diagram', 'Instrument Loop Diagram')], default='piping_instrumentation', max_length=25)),
                ('revision', models.CharField(default='A', help_text='Drawing revision', max_length=10)),
                ('sheet_number', models.CharField(blank=True, help_text="Sheet number (e.g., '1 of 3')", max_length=20)),
                ('original_file', models.FileField(help_text='Upload P&ID file (PDF, DWG, PNG, JPG, TIFF)', upload_to='pid_diagrams/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwg', 'png', 'jpg', 'jpeg', 'tiff'])])),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analysis Complete'), ('reviewed', 'Engineering Review'), ('approved', 'Approved'), ('revision_required', 'Revision Required'), ('error', 'Processing Error')], default='uploaded', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_errors_found', models.IntegerField(default=0)),
                ('critical_errors', models.IntegerField(default=0)),
                ('high_priority_errors', models.IntegerField(default=0)),
                ('medium_priority_errors', models.IntegerField(default=0)),
                ('low_priority_errors', models.IntegerField(default=0)),
                ('process_area', models.CharField(blank=True, help_text="Process area (e.g., 'Gas Processing')", max_length=100)),
                ('operating_pressure', models.CharField(blank=True, help_text='Operating pressure range', max_length=50)),
                ('operating_temperature', models.CharField(blank=True, help_text='Operating temperature range', max_length=50)),
                ('design_phase', models.CharField(blank=True, help_text='Engineering phase (FEED, Detail, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P&ID Diagram',
                'verbose_name_plural': 'P&ID Diagrams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('llm_model', models.CharField(default='gpt-4', max_length=100)),
                ('analysis_depth', models.CharField(choices=[('quick', 'Quick Scan'), ('standard', 'Standard Analysis'), ('deep', 'Deep Analysis')], default='standard', max_length=20)),
                ('include_recommendations', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('initiated', 'Analysis Initiated'), ('preprocessing', 'Preprocessing Diagram'), ('ocr_processing', 'OCR Text Extraction'), ('element_detection', 'Element Detection'), ('error_analysis', 'Error Analysis'), ('post_processing', 'Post Processing'), ('completed', 'Analysis Completed'), ('failed', 'Analysis Failed')], default='initiated', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('total_elements_detected', models.IntegerField(default=0)),
                ('total_errors_found', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to='pid_analysis.piddiagram')),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'verbose_name_plural': 'Analysis Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Project name (e.g., 'Haradh Gas Plant Expansion')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description and scope')),
                ('project_type', models.CharField(choices=[('upstream', 'Upstream (Exploration & Production)'), ('midstream', 'Midstream (Transportation & Storage)'), ('downstream', 'Downstream (Refining & Petrochemicals)'), ('lng', 'LNG (Liquefied Natural Gas)'), ('offshore', 'Offshore Platform'), ('onshore', 'Onshore Facility'), ('pipeline', 'Pipeline System'), ('refinery', 'Refinery Unit'), ('petrochemical', 'Petrochemical Plant')], default='upstream', max_length=20)),
                ('engineering_standard', models.CharField(choices=[('isa_5_1', 'ISA-5.1 (Instrumentation Symbols)'), ('iso_10628', 'ISO 10628 (Flow Diagrams)'), ('iec_62424', 'IEC 62424 (Process Control Systems)'), ('api_14c', 'API 14C (Offshore Safety Systems)'), ('asme_y14_2', 'ASME Y14.2 (Line Conventions)'), ('shell_dcs', 'Shell DEP (Design Engineering Practice)'), ('exxonmobil_pgs', 'ExxonMobil PGS Standards'), ('bp_gsp', 'BP GSP (General Specification)'), ('custom', 'Custom Company Standards')], default='isa_5_1', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Oil/Gas field name', max_length=100)),
                ('facility_code', models.CharField(blank=True, help_text='Facility identifier', max_length=20)),
                ('process_unit', models.CharField(blank=True, help_text='Process unit description', max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('engineering_contractor', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P&ID Project',
                'verbose_name_plural': 'P&ID Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='piddiagram',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='pid_analysis.pidproject'),
        ),
        migrations.CreateModel(
            name='PIDAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_title', models.CharField(help_text='Brief error description', max_length=200)),
                ('error_description', models.TextField(help_text='Detailed error description')),
                ('root_cause', models.TextField(help_text='Root cause analysis')),
                ('recommended_fix', models.TextField(help_text='Engineering recommendation')),
                ('severity_level', models.CharField(choices=[('critical', 'Critical - Safety/Operations Impact'), ('high', 'High - Major Engineering Issue'), ('medium', 'Medium - Standard Compliance'), ('low', 'Low - Minor Improvement'), ('info', 'Information - Best Practice')], max_length=10)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('element_tag', models.CharField(blank=True, help_text='Equipment/instrument tag', max_length=50)),
                ('line_number', models.CharField(blank=True, help_text='Piping line number', max_length=50)),
                ('coordinates_x', models.FloatField(blank=True, help_text='X coordinate in diagram', null=True)),
                ('coordinates_y', models.FloatField(blank=True, help_text='Y coordinate in diagram', null=True)),
                ('violated_standard', models.CharField(blank=True, help_text='Violated engineering standard', max_length=100)),
                ('standard_reference', models.CharField(blank=True, help_text='Standard clause/section', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected - False Positive'), ('fixed', 'Fixed'), ('deferred', 'Deferred to Future Revision')], default='open', max_length=15)),
                ('review_comments', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('llm_model_used', models.CharField(blank=True, help_text='LLM model used for detection', max_length=100)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pid_analysis.errorcategory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_errors', to=settings.AUTH_USER_MODEL)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='pid_analysis.piddiagram')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-severity_level', '-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['diagram', 'severity_level'], name='pid_analysi_diagram_a61fc8_idx'), models.Index(fields=['category', 'status'], name='pid_analysi_categor_f0a87a_idx'), models.Index(fields=['element_tag'], name='pid_analysi_element_495bc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PIDElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('pump', 'Pump'), ('compressor', 'Compressor'), ('vessel', 'Pressure Vessel'), ('tank', 'Storage Tank'), ('heat_exchanger', 'Heat Exchanger'), ('turbine', 'Turbine'), ('generator', 'Generator'), ('separator', 'Separator'), ('filter', 'Filter'), ('knockout_drum', 'Knockout Drum'), ('flow_transmitter', 'Flow Transmitter (FT)'), ('pressure_transmitter', 'Pressure Transmitter (PT)'), ('temperature_transmitter', 'Temperature Transmitter (TT)'), ('level_transmitter', 'Level Transmitter (LT)'), ('flow_indicator', 'Flow Indicator (FI)'), ('pressure_indicator', 'Pressure Indicator (PI)'), ('temperature_indicator', 'Temperature Indicator (TI)'), ('control_valve', 'Control Valve'), ('safety_valve', 'Safety/Relief Valve'), ('piping_line', 'Piping Line'), ('valve_gate', 'Gate Valve'), ('valve_ball', 'Ball Valve'), ('valve_globe', 'Globe Valve'), ('valve_check', 'Check Valve'), ('valve_butterfly', 'Butterfly Valve'), ('orifice_plate', 'Orifice Plate')], max_length=30)),
                ('tag_number', models.CharField(help_text='Element tag number', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, help_text='Size/rating', max_length=50)),
                ('specification', models.CharField(blank=True, help_text='Material/spec', max_length=100)),
                ('service', models.CharField(blank=True, help_text='Process service', max_length=100)),
                ('coordinates_x', models.FloatField(blank=True, null=True)),
                ('coordinates_y', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('extracted_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='pid_analysis.piddiagram')),
            ],
            options={
                'verbose_name': 'P&ID Element',
                'verbose_name_plural': 'P&ID Elements',
                'ordering': ['element_type', 'tag_number'],
                'unique_together': {('diagram', 'tag_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='piddiagram',
            unique_together={('project', 'drawing_number', 'revision')},
        ),
    ]
