# Generated by Django 5.2.8 on 2025-11-15 05:44

import core.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0002_create_rejlers_user_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pidproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='piddiagram',
            name='original_file',
            field=models.FileField(help_text='Upload P&ID file (PDF, DWG, DXF, PNG, JPG, TIFF)', upload_to=core.storage.get_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwg', 'dxf', 'png', 'jpg', 'jpeg', 'tiff'])]),
        ),
    ]
