# Generated by Django 4.2.16 on 2025-11-18 06:47

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('oil_gas', 'Oil & Gas'), ('petrochemical', 'Petrochemical'), ('refinery', 'Refinery'), ('offshore', 'Offshore Platform'), ('pipeline', 'Pipeline'), ('facility', 'Process Facility'), ('other', 'Other')], default='oil_gas', max_length=50)),
                ('engineering_standard', models.CharField(choices=[('iso', 'ISO Standard'), ('api', 'API Standard'), ('asme', 'ASME Standard'), ('astm', 'ASTM Standard'), ('dnv', 'DNV Standard'), ('custom', 'Custom Standard')], default='iso', max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=50)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('drawing_number', models.CharField(blank=True, max_length=100)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(choices=[('pid', 'P&ID Diagram'), ('isometric', 'Isometric Drawing'), ('plan', 'Plan View'), ('elevation', 'Elevation View'), ('section', 'Section View'), ('detail', 'Detail Drawing'), ('specification', 'Technical Specification'), ('datasheet', 'Equipment Datasheet'), ('manual', 'Operation Manual'), ('report', 'Engineering Report'), ('other', 'Other Document')], max_length=50)),
                ('discipline', models.CharField(blank=True, max_length=100)),
                ('plant_area', models.CharField(blank=True, max_length=200)),
                ('system_tag', models.CharField(blank=True, max_length=100)),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('archived', 'Archived')], default='uploading', max_length=20)),
                ('quality_level', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('issued', 'Issued for Construction'), ('as_built', 'As-Built')], default='draft', max_length=20)),
                ('ocr_text', models.TextField(blank=True)),
                ('metadata_extracted', models.JSONField(blank=True, default=dict)),
                ('processing_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=200)),
                ('analysis_types', models.JSONField(default=list)),
                ('configuration', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('total_documents', models.IntegerField(default=0)),
                ('completed_documents', models.IntegerField(default=0)),
                ('failed_documents', models.IntegerField(default=0)),
                ('total_equipment_found', models.IntegerField(default=0)),
                ('total_issues_found', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('documents', models.ManyToManyField(related_name='analysis_sessions', to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to='documents.project')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('symbol_detection', 'Symbol Detection'), ('equipment_identification', 'Equipment Identification'), ('piping_analysis', 'Piping & Instrumentation Analysis'), ('safety_review', 'Safety & Compliance Review'), ('completeness_check', 'Drawing Completeness Check'), ('standard_compliance', 'Standards Compliance'), ('full_analysis', 'Complete P&ID Analysis')], max_length=50)),
                ('configuration', models.JSONField(default=dict)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('confidence_level', models.CharField(blank=True, choices=[('low', 'Low Confidence'), ('medium', 'Medium Confidence'), ('high', 'High Confidence'), ('very_high', 'Very High Confidence')], max_length=20)),
                ('results', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('equipment_detected', models.JSONField(default=list)),
                ('symbols_detected', models.JSONField(default=list)),
                ('piping_detected', models.JSONField(default=list)),
                ('issues_found', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('compliance_notes', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('summary', 'Executive Summary'), ('detailed', 'Detailed Technical Report'), ('compliance', 'Compliance Assessment'), ('equipment_list', 'Equipment Schedule'), ('issues_report', 'Issues & Recommendations'), ('comparison', 'Drawing Comparison'), ('progress', 'Project Progress Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('html', 'HTML Report'), ('json', 'JSON Data')], max_length=10)),
                ('configuration', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, upload_to='reports/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='generating', max_length=20)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analyses', models.ManyToManyField(related_name='reports', to='documents.analysis')),
                ('documents', models.ManyToManyField(related_name='reports', to='documents.document')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='documents.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'report_type'], name='documents_r_project_e2bc7d_idx'), models.Index(fields=['status', 'created_at'], name='documents_r_status_288d36_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type', 'status'], name='documents_p_project_153f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by', 'status'], name='documents_p_created_22e8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'document_type'], name='documents_d_project_4f1b21_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'uploaded_at'], name='documents_d_status_7e2894_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['drawing_number'], name='documents_d_drawing_dfeeda_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('drawing_number__isnull', False), models.Q(('drawing_number', ''), _negated=True)), fields=('project', 'drawing_number', 'revision'), name='unique_drawing_per_project'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['document', 'analysis_type'], name='documents_a_documen_3f745c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['status', 'created_at'], name='documents_a_status_248373_idx'),
        ),
    ]
